# Generated by Django 5.2.7 on 2025-10-25 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('motor', 'Motor'), ('transmissao', 'Transmissão e Embreagem'), ('suspensao', 'Suspensão e Direção'), ('freios', 'Freios'), ('eletrica', 'Sistema Elétrico'), ('ar_condicionado', 'Ar-condicionado e Climatização'), ('carroceria', 'Carroceria e Itens Externos'), ('fluidos', 'Fluidos e Manutenções Gerais')], max_length=30, verbose_name='categoria')),
                ('nome', models.CharField(max_length=100, verbose_name='nome da peça')),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='modelo')),
                ('ano', models.PositiveIntegerField(verbose_name='ano')),
                ('placa', models.CharField(blank=True, max_length=10, verbose_name='placa')),
                ('km_atual', models.PositiveIntegerField(default=0, verbose_name='quilometragem atual')),
                ('combustivel', models.CharField(blank=True, max_length=20, verbose_name='combustível')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='RegistroManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('km', models.PositiveIntegerField(verbose_name='quilometragem')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço (R$)')),
                ('troca', models.BooleanField(default=False, verbose_name='troca (sim/não)')),
                ('garantia_meses', models.PositiveIntegerField(blank=True, null=True, verbose_name='tempo de garantia (meses)')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivecar.peca', verbose_name='peça')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivecar.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'Registro de Manutenção',
                'verbose_name_plural': 'Registros de Manutenção',
                'ordering': ['-data', '-km'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('km', 'Por quilometragem'), ('tempo', 'Por tempo')], max_length=10, verbose_name='tipo')),
                ('km_previsto', models.PositiveIntegerField(blank=True, null=True, verbose_name='quilometragem prevista')),
                ('data_prevista', models.DateField(blank=True, null=True, verbose_name='data prevista')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivecar.veiculo', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
            },
        ),
    ]
