# Generated by Django 5.2.7 on 2025-10-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivecar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromanutencao',
            name='alerta_ativo',
            field=models.BooleanField(default=False, help_text='Ativar alerta para próxima manutenção', verbose_name='alerta ativo'),
        ),
        migrations.AddField(
            model_name='registromanutencao',
            name='alerta_intervalo_km',
            field=models.PositiveIntegerField(blank=True, help_text='A cada quantos KM deve ser feita a próxima manutenção', null=True, verbose_name='intervalo em KM'),
        ),
        migrations.AddField(
            model_name='registromanutencao',
            name='alerta_intervalo_meses',
            field=models.PositiveIntegerField(blank=True, help_text='A cada quantos meses deve ser feita a próxima manutenção', null=True, verbose_name='intervalo em meses'),
        ),
    ]
