# Generated by Django 5.2.4 on 2025-10-26 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivecar', '0002_registromanutencao_alerta_ativo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registromanutencao',
            name='alerta_intervalo_km',
        ),
        migrations.RemoveField(
            model_name='registromanutencao',
            name='alerta_intervalo_meses',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='usuario',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='registromanutencao',
            name='alerta_ativo',
            field=models.BooleanField(default=False, verbose_name='alerta ativo'),
        ),
    ]
