# Generated by Django 5.2.4 on 2025-10-26 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivecar', '0003_remove_registromanutencao_alerta_intervalo_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(blank=True, choices=[('GASOLINA', 'Gasolina'), ('ALCOOL', 'Álcool / Etanol'), ('FLEX', 'Flex (Gasolina/Etanol)'), ('DIESEL', 'Diesel'), ('GNV', 'GNV (Gás Natural Veicular)'), ('HIBRIDO', 'Híbrido'), ('ELETRICO', 'Elétrico')], max_length=20, verbose_name='combustível'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
    ]
