# Generated by Django 5.2.4 on 2025-11-02 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivecar', '0005_marca_veiculo_marca_legado_veiculo_modelo_legado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('motor', 'Motor e Sistema de Injeção'), ('transmissao', 'Transmissão e Embreagem'), ('suspensao', 'Suspensão e Direção'), ('freios', 'Sistema de Freios'), ('eletrica', 'Sistema Elétrico e Eletrônico'), ('ar_condicionado', 'Ar-condicionado e Climatização'), ('carroceria', 'Funilaria e Pintura'), ('pneus_rodas', 'Pneus e Rodas'), ('manutencao_geral', 'Manutenção Geral')], max_length=30, verbose_name='categoria')),
                ('nome', models.CharField(max_length=150, verbose_name='nome do serviço')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='registromanutencao',
            name='tipo',
            field=models.CharField(choices=[('peca', 'Peça'), ('servico', 'Serviço')], default='peca', max_length=10, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='registromanutencao',
            name='peca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivecar.peca', verbose_name='peça'),
        ),
        migrations.AlterField(
            model_name='registromanutencao',
            name='troca',
            field=models.BooleanField(default=False, help_text='Marque se foi uma troca ou substituição', verbose_name='troca/substituição'),
        ),
        migrations.AddField(
            model_name='registromanutencao',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivecar.servico', verbose_name='serviço'),
        ),
    ]
