# Generated by Django 5.2.4 on 2025-11-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivecar', '0006_servico_registromanutencao_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registromanutencao',
            name='local_lavagem',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='local da lavagem'),
        ),
        migrations.AddField(
            model_name='registromanutencao',
            name='tipo_lavagem',
            field=models.CharField(blank=True, choices=[('lavagem_simples', '🚿 Lavagem simples'), ('lavagem_completa', '🧽 Lavagem completa'), ('so_interna', '🏠 Só interna'), ('so_externa', '🚗 Só externa'), ('enceramento', '✨ Enceramento'), ('detalhamento', '💎 Detalhamento'), ('lavagem_motor', '🔧 Lavagem de motor'), ('limpeza_vidros', '🪟 Limpeza de vidros'), ('limpeza_rodas', '🛞 Limpeza de rodas/pneus'), ('lavagem_seco', '🧴 Lavagem à seco')], max_length=20, null=True, verbose_name='tipo de lavagem'),
        ),
        migrations.AlterField(
            model_name='registromanutencao',
            name='tipo',
            field=models.CharField(choices=[('peca', 'Peça'), ('servico', 'Serviço'), ('lavagem', 'Lavagem')], default='peca', max_length=10, verbose_name='tipo'),
        ),
    ]
