# Generated by Django 5.2.4 on 2025-11-02 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivecar', '0007_add_lavagem_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalLavagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Lava Jato do João - Rua das Flores, 123', max_length=200, verbose_name='nome do local')),
                ('endereco', models.TextField(blank=True, help_text='Endereço completo (opcional)', verbose_name='endereço')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Local de Lavagem',
                'verbose_name_plural': 'Locais de Lavagem',
                'ordering': ['nome'],
                'unique_together': {('usuario', 'nome')},
            },
        ),
    ]
